.bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat **/*.gemspec
    populate_script: bundle update

remark_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: yarn install
  remark_script: yarn run remark

rubocop_task:
  container:
    image: ruby:2.7
  <<: *bundle_cache
  rubocop_script: bundle exec rubocop

test_task:
  depends_on:
    - remark
    - rubocop
  container:
    matrix:
      image: ruby:2.4
      image: ruby:2.5
      image: ruby:2.6
      image: ruby:2.7
  <<: *bundle_cache
  test_script: bundle exec rake
